### ISSUE TITLE
Use pyramid-like patterns

### ISSUE THREAD

**Issue by vangheem** [plone/plone.server#11]
I think we should focus on using more pyramid-like patterns. It will help people feel more familiar with configuring and building applications on top of it.

Some things specifically where I think this applies:
- authentication/authorization, zope.authentication is lacking and I'm not sure it's an interface we want to follow anyways
- do not use zcml
- provide configuration object
- includeme idiom could also be used
- maybe move json api config to decorators?

Any thoughts?

**Comment by datakurre** [comment]
These difficult issues. It's hard to replace ZTK-packages / conventions without replicating similar features by ourselves. And currently we don't test our code well enough to qualify.

zope.authentication
- zope.securitypolicy depends on zope.authentication interfaces
- zope.securitypolicy implements the security model we've used to in Plone
- I'd be careful in reinventing / reimplementing that

zcml
- as long as we use ZTK, we must support ZCML
- what could replace ZCML? venusian does nothing by itself, pyramid has its own venusian based configurator, pyramid_zcml depends on pyramid configurator
- I did propose my zope.configuration based/compatible venusianconfiguration at Barcelona Sprint, but it just scared everyone, and I had to refactor it out

@bloodbare needs to defend JSON-configuration; IMO JSON is no better than XML for humans to write :) (generated JSON is ok)

IMO, if we come up with Python based configuration, then decorators and includeme configuration should be obvious.

**Comment by datakurre** [comment]
<strike>
I'm lucky to have some rare spare time this weekend, so I'll try out an another moonshot:
- asyncio + uvloop + httptools + something for fast minimal asyncio HTTP server
- two threads + processpool
- main thread with asyncio loop is just the HTTP server (similarly to ZServer)
- one worker thread with asyncio loop will route and process requests with single ZODB connection
- asyncio process worker with configurable pool size for handling stateless processing
- somehow I force only one active transaction on the connection and make it convenient to "release" the ZODB connection as possible, possible make a savepoint of uncommitted changes, and make it posibble to continue frozen transaction later (unless there have been conflicts)
  </strike>

Cancelled by changes in family schedules. Was too good to be true :) Yet, at some point I must experiment, if pyramid could be used with asyncio and without WSGI with a pattern that works with ZODB (default patterns won't work because of all the issues we have with plone.server). And if that works, that pattern could also be adapted to plone.server with ZTK (I just want to try it out with minimal stack at first).

**Comment by vangheem** [comment]
Maybe I just need to build on zope.authentication more. Or we still use zope.authentication but build pyramid-like patterns with it.

I'm just not very happy on initial look for using it. I've been playing with implementing https://github.com/pyrenees/pserver.zodbusers and find the current interfaces a little crud. I'd like to have a more elegant solution.

I don't want to re-implement anything--but barrow on the ideas... Use what works and has been a more popular choice.

That being said, you're point about ZCA and ZCML are well taken. I wish I would have noticed your discussion on the venusian zope configuration--might help me understand what would be best now.

**Comment by datakurre** [comment]
Did you already look into zope.principalregistry on how it implements non-persistent registry?

**Comment by vangheem** [comment]
No, I didn't. It looks like it could help in some cases.

**Comment by bloodbare** [comment]
On plone.server there is two JSON:

One for the REST API : its main idea is that can be readed easier in code and we can generate documentation easily to see the API from it. @sneridagh was working on this parsing and generation.

One for the starting up configuration : This configuration is mainly written by machine on docker containers, so it needs to be something easy to serialize and deserialize. In my opinion JSON is the tool for this configuration.

I'm not fan of any format, just like the idea of use what needs to be used to make it easy and document it properly. 

I like the non-persitent registry ! :)
